# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
variables:
  azureSubscription: 'Azure subscription 1(c24d5ea5-e90d-4220-908f-60b4f697f89b)' 
stages:
  - stage: DeployResourceGroup
    displayName: 'Deploy Resource Group'
    jobs:
      - job: DeployRG
        displayName: 'Deploy Resource Group'
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: $(azureSubscription)
              location: '[parameters from JSON file]'
              templateLocation: 'Linked artifact'
              csmFile: 'https://github.com/Jadyle/DevEnv-UQAC/blob/main/KeyVault/ressourcegroup.json'         # Path to resource group template
              csmParametersFile: 'https://github.com/Jadyle/DevEnv-UQAC/blob/main/KeyVault/ressourcegroup.parameters.json' # Path to parameter file for the resource group
              deploymentMode: 'Incremental'

  - stage: DeployKeyVault
    displayName: 'Deploy Key Vault'
    dependsOn: DeployResourceGroup
    jobs:
      - job: DeployKV
        displayName: 'Deploy Key Vault'
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(azureSubscription)
              resourceGroupName: '[rgName from parameters JSON]'
              location: '[parameters from JSON file]'
              templateLocation: 'Linked artifact'
              csmFile: 'https://github.com/Jadyle/DevEnv-UQAC/blob/main/KeyVault/keyvault.json'              # Path to Key Vault template
              csmParametersFile: 'https://github.com/Jadyle/DevEnv-UQAC/blob/main/KeyVault/keyvault.parameters.json' # Path to parameter file for Key Vault
              deploymentMode: 'Incremental'