# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default


variables:
  azureSubscription: 'Azure subscription 1(c24d5ea5-e90d-4220-908f-60b4f697f89b)'
  location: 'canada central'
  ressourceGroupTemplate: 'KeyVault/ressourcegroup.json'
  ressourceGroupParameters: 'KeyVault/ressourcegroup.parameters.json'
  ressourceGroupName: 'ressource-group-deployement-keyvault'
  keyVaultTemplate: 'KeyVault/keyvault.json'
  keyVaultParameters: 'KeyVault/keyvault.parameters.json'
stages:
  - stage: DeployResourceGroup
    displayName: 'Deploy Resource Group'
    jobs:
      - job: DeployRG
        displayName: 'Deploy Resource Group'
        steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: $(azureSubscription)
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(ressourceGroupTemplate)'         # Path to resource group template
              csmParametersFile: '$(ressourceGroupParameters)' # Path to parameter file for the resource group
              deploymentMode: 'Incremental'

  - stage: DeployKeyVault 
    displayName: 'Deploy Key Vault'
    dependsOn: DeployResourceGroup
    jobs:
      - job: DeployKV
        displayName: 'Deploy Key Vault'
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(azureSubscription)
              resourceGroupName: '$(ressourceGroupName)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(keyVaultTemplate)'         # Path to Key Vault template
              csmParametersFile: '$(keyVaultParameters)' # Path to parameter file for the Key Vault
              deploymentMode: 'Incremental'